# This is a basic workflow that is manually triggered

name: Download Manual workflow

on:
  # release:
  #   types: published
  workflow_dispatch:
  
jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    # runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install packaging
    # - run: pip install pyserial
    - run: pip install requests
    - name: Build Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python main.py

    # - name: Create ZIP file
    #   run: |
    #     mkdir release
    #     cp -r .downloads/* release/
    #     zip -r release.zip release
    - name: Zip the Build
      run: zip -r ${{ secrets.ReleaseZipName }} .downloads/*


    # - name: Upload Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #       upload_url: ${{ github.event.release.upload_url }}
    #       assets: .downloads/package_esp32_index.json
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Upload Release Asset
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     # upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: ./${{ secrets.ReleaseZipName }}.zip
    #     asset_name: ${{ secrets.ReleaseZipName }}.zip
    #     asset_content_type: application/zip   

    - name: create github release
      id: new_release
      uses: softprops/action-gh-release@v2.0.8
      with:
        name: latest
        make_latest: true
        files: ${{ secrets.ReleaseZipName }}.zip
      
